name: PushTag

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  push_version:
    name: Push version tag Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: snakesoft/djanginx

      - name: Set MAJOR
        run: echo "MAJOR=${GITHUB_REF_NAME%%.*}" >> $GITHUB_ENV

      - name: Set MINOR
        run: echo "MINOR=${GITHUB_REF_NAME%.*}" >> $GITHUB_ENV

      - name: Set MICRO
        run: echo "MICRO=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Set HASH
        run: echo "HASH=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.MICRO }}
            HASH=${{ env.hash }}
          tags: |
            snakesoft/djanginx:${{ env.MAJOR }}
            snakesoft/djanginx:${{ env.MINOR }}
            snakesoft/djanginx:${{ env.MICRO }}
